### PR TITLE
Move swate manual to knowledge base

### PR DESCRIPTION
**Pull request by Brilator**
- removed user docs here and moved them to kb https://github.com/nfdi4plants/nfdi4plants.knowledgebase/pull/89
- adapted index page and sidebar slightly to align with arc commander dev docs (room for improvement)

### CODE REVIEW

**Comment by Brilator** [comment]
@Freymaurer Cannot assign you as reviewer, but I think we're safe to delete the UserDocs here.

**Review by Freymaurer — APPROVED** [review]

**Comment by Freymaurer** [comment]
@Brilator the current Swate version links to this wiki for most topics. Deleting everything now will break most links. 

1. Please open a Swate issue, to request updating the Swate docs links.
2. Please make an announcement in Teams General that most user docs will move should anyone reference these.

EDIT: After the Swate issue is done i will merge this PR. Please mention the link to this PR in the issue.

**Comment by Brilator** [comment]
> Please open a Swate issue, to request updating the Swate docs links.

https://github.com/nfdi4plants/Swate/issues/272

**Comment by Brilator** [comment]
> Please make an announcement in Teams General that most user docs will move should anyone reference these.

Done. Good point. 

Isn't there an automated way to redirect all attempts to visit UserDocs/** to the knowledge base?

**Comment by Freymaurer** [comment]
> Isn't there an automated way to redirect all attempts to visit UserDocs/** to the knowledge base?

There might be a possibility to do this: https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7

Unfortunately, I am completely busy at the moment and cannot make the effort myself.

**Pull request closed without merging**
